USE [master]
GO

/****** Object:  Database [SchoolSystem]    Script Date: 6/8/2023 7:34:49 PM ******/
CREATE DATABASE [SchoolSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SchoolSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLSERVER2017\MSSQL\DATA\SchoolSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SchoolSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLSERVER2017\MSSQL\DATA\SchoolSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SchoolSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SchoolSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SchoolSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SchoolSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SchoolSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SchoolSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [SchoolSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SchoolSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SchoolSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SchoolSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SchoolSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SchoolSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SchoolSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SchoolSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SchoolSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SchoolSystem] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SchoolSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SchoolSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SchoolSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SchoolSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SchoolSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SchoolSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SchoolSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SchoolSystem] SET RECOVERY FULL 
GO

ALTER DATABASE [SchoolSystem] SET  MULTI_USER 
GO

ALTER DATABASE [SchoolSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SchoolSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SchoolSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SchoolSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SchoolSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SchoolSystem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SchoolSystem] SET QUERY_STORE = ON
GO

ALTER DATABASE [SchoolSystem] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SchoolSystem] SET  READ_WRITE 
GO


